# Generated by Django 5.1 on 2024-09-09 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 12, 47, 43, 584, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
